"""Official XVF3800 USB control commands used by the ROS wrapper."""

from dataclasses import dataclass


CONTROL_SUCCESS = 0
SERVICER_COMMAND_RETRY = 64


@dataclass(frozen=True)
class CommandSpec:
    resid: int
    cmdid: int
    count: int
    access: str
    data_type: str
    description: str


COMMANDS = {
    "VERSION": CommandSpec(48, 0, 3, "ro", "uint8", "Firmware version"),
    "BLD_MSG": CommandSpec(48, 1, 50, "ro", "char", "Build message"),
    "BLD_HOST": CommandSpec(48, 2, 30, "ro", "char", "Build host"),
    "BLD_REPO_HASH": CommandSpec(48, 3, 40, "ro", "char", "Repository hash"),
    "BLD_MODIFIED": CommandSpec(48, 4, 6, "ro", "char", "Repository modified flag"),
    "BOOT_STATUS": CommandSpec(48, 5, 3, "ro", "char", "Boot source"),
    "TEST_CORE_BURN": CommandSpec(48, 6, 1, "rw", "uint8", "Internal test command"),
    "REBOOT": CommandSpec(48, 7, 1, "wo", "uint8", "Reboot and reset params"),
    "USB_BIT_DEPTH": CommandSpec(48, 8, 2, "rw", "uint8", "USB bit depth"),
    "SAVE_CONFIGURATION": CommandSpec(48, 9, 1, "wo", "uint8", "Save config"),
    "CLEAR_CONFIGURATION": CommandSpec(48, 10, 1, "wo", "uint8", "Clear config"),
    "AEC_NUM_MICS": CommandSpec(33, 71, 1, "ro", "int32", "Number of microphones"),
    "AEC_NUM_FARENDS": CommandSpec(33, 72, 1, "ro", "int32", "Number of far ends"),
    "AEC_MIC_ARRAY_TYPE": CommandSpec(33, 73, 1, "ro", "int32", "Mic array type"),
    "AEC_MIC_ARRAY_GEO": CommandSpec(33, 74, 12, "ro", "float", "Mic coordinates"),
    "AEC_AZIMUTH_VALUES": CommandSpec(33, 75, 4, "ro", "radians", "Beam azimuths"),
    "AEC_CURRENT_IDLE_TIME": CommandSpec(33, 77, 1, "ro", "uint32", "AEC idle time"),
    "AEC_MIN_IDLE_TIME": CommandSpec(33, 78, 1, "ro", "uint32", "AEC minimum idle time"),
    "AEC_RESET_MIN_IDLE_TIME": CommandSpec(33, 79, 1, "wo", "uint32", "Reset AEC min idle"),
    "AEC_SPENERGY_VALUES": CommandSpec(33, 80, 4, "ro", "float", "Speech energy"),
    "AEC_FIXEDBEAMSAZIMUTH_VALUES": CommandSpec(33, 81, 2, "rw", "radians", "Fixed beam azimuth"),
    "AEC_FIXEDBEAMSELEVATION_VALUES": CommandSpec(33, 82, 2, "rw", "radians", "Fixed beam elevation"),
    "AEC_FIXEDBEAMSGATING": CommandSpec(33, 83, 1, "rw", "uint8", "Fixed beam gating"),
    "AEC_AECPATHCHANGE": CommandSpec(33, 0, 1, "ro", "int32", "AEC path change"),
    "AEC_HPFONOFF": CommandSpec(33, 1, 1, "rw", "int32", "High-pass filter"),
    "AEC_AECSILENCELEVEL": CommandSpec(33, 2, 2, "rw", "float", "Silence level"),
    "AEC_AECCONVERGED": CommandSpec(33, 3, 1, "ro", "int32", "AEC converged"),
    "AEC_AECEMPHASISONOFF": CommandSpec(33, 4, 1, "rw", "int32", "AEC emphasis"),
    "AEC_FAR_EXTGAIN": CommandSpec(33, 5, 1, "rw", "float", "Far end gain"),
    "AEC_PCD_COUPLINGI": CommandSpec(33, 6, 1, "rw", "float", "PCD coupling"),
    "AEC_PCD_MINTHR": CommandSpec(33, 7, 1, "rw", "float", "PCD min threshold"),
    "AEC_PCD_MAXTHR": CommandSpec(33, 8, 1, "rw", "float", "PCD max threshold"),
    "AEC_RT60": CommandSpec(33, 9, 1, "ro", "float", "RT60 estimate"),
    "AEC_ASROUTONOFF": CommandSpec(33, 35, 1, "rw", "int32", "ASR output enable"),
    "AEC_ASROUTGAIN": CommandSpec(33, 36, 1, "rw", "float", "ASR output gain"),
    "AEC_FIXEDBEAMSONOFF": CommandSpec(33, 37, 1, "rw", "int32", "Fixed beam mode"),
    "AEC_FIXEDBEAMNOISETHR": CommandSpec(33, 38, 2, "rw", "float", "Fixed beam noise threshold"),
    "AUDIO_MGR_MIC_GAIN": CommandSpec(35, 0, 1, "rw", "float", "Mic gain"),
    "AUDIO_MGR_REF_GAIN": CommandSpec(35, 1, 1, "rw", "float", "Reference gain"),
    "AUDIO_MGR_CURRENT_IDLE_TIME": CommandSpec(35, 2, 1, "ro", "int32", "Audio manager idle time"),
    "AUDIO_MGR_MIN_IDLE_TIME": CommandSpec(35, 3, 1, "ro", "int32", "Audio manager min idle"),
    "AUDIO_MGR_RESET_MIN_IDLE_TIME": CommandSpec(35, 4, 1, "wo", "int32", "Reset audio manager min idle"),
    "MAX_CONTROL_TIME": CommandSpec(35, 5, 1, "ro", "int32", "Max control time"),
    "RESET_MAX_CONTROL_TIME": CommandSpec(35, 6, 1, "wo", "int32", "Reset max control time"),
    "I2S_CURRENT_IDLE_TIME": CommandSpec(35, 7, 1, "ro", "int32", "I2S idle time"),
    "I2S_MIN_IDLE_TIME": CommandSpec(35, 8, 1, "ro", "int32", "I2S min idle"),
    "I2S_RESET_MIN_IDLE_TIME": CommandSpec(35, 9, 1, "wo", "int32", "Reset I2S min idle"),
    "I2S_INPUT_PACKED": CommandSpec(35, 10, 1, "rw", "uint8", "Packed input"),
    "AUDIO_MGR_SELECTED_AZIMUTHS": CommandSpec(35, 11, 2, "ro", "radians", "Selected azimuths"),
    "AUDIO_MGR_SELECTED_CHANNELS": CommandSpec(35, 12, 2, "rw", "uint8", "Selected channels"),
    "AUDIO_MGR_OP_PACKED": CommandSpec(35, 13, 2, "rw", "uint8", "Packed output"),
    "AUDIO_MGR_OP_UPSAMPLE": CommandSpec(35, 14, 2, "rw", "uint8", "Upsample output"),
    "AUDIO_MGR_OP_L": CommandSpec(35, 15, 2, "rw", "uint8", "Left output mux"),
    "AUDIO_MGR_OP_R": CommandSpec(35, 19, 2, "rw", "uint8", "Right output mux"),
    "AUDIO_MGR_OP_ALL": CommandSpec(35, 23, 12, "rw", "uint8", "All output muxes"),
    "I2S_INACTIVE": CommandSpec(35, 24, 1, "ro", "uint8", "I2S inactive flag"),
    "AUDIO_MGR_FAR_END_DSP_ENABLE": CommandSpec(35, 25, 1, "rw", "uint8", "Far end DSP"),
    "AUDIO_MGR_SYS_DELAY": CommandSpec(35, 26, 1, "rw", "int32", "System delay"),
    "I2S_DAC_DSP_ENABLE": CommandSpec(35, 27, 1, "rw", "uint8", "DAC DSP enable"),
    "GPI_READ_VALUES": CommandSpec(20, 0, 3, "ro", "uint8", "GPIO inputs"),
    "GPO_READ_VALUES": CommandSpec(20, 0, 5, "ro", "uint8", "GPIO outputs"),
    "GPO_WRITE_VALUE": CommandSpec(20, 1, 2, "wo", "uint8", "Write GPO pin"),
    "GPO_PORT_PIN_INDEX": CommandSpec(20, 2, 2, "rw", "uint32", "GPO port/pin index"),
    "GPO_PIN_VAL": CommandSpec(20, 3, 3, "wo", "uint8", "Write one GPO pin"),
    "GPO_PIN_ACTIVE_LEVEL": CommandSpec(20, 4, 1, "rw", "uint32", "GPO active level"),
    "LED_EFFECT": CommandSpec(20, 12, 1, "rw", "uint8", "LED effect"),
    "LED_BRIGHTNESS": CommandSpec(20, 13, 1, "rw", "uint8", "LED brightness"),
    "LED_GAMMIFY": CommandSpec(20, 14, 1, "rw", "uint8", "LED gamma correction"),
    "LED_SPEED": CommandSpec(20, 15, 1, "rw", "uint8", "LED speed"),
    "LED_COLOR": CommandSpec(20, 16, 1, "rw", "uint32", "LED color"),
    "LED_DOA_COLOR": CommandSpec(20, 17, 2, "rw", "uint32", "LED DoA color"),
    "DOA_VALUE": CommandSpec(20, 18, 2, "ro", "uint16", "DoA and VAD"),
    "LED_RING_COLOR": CommandSpec(20, 19, 12, "rw", "uint32", "LED ring colors"),
    "PP_CURRENT_IDLE_TIME": CommandSpec(17, 70, 1, "ro", "uint32", "PP idle time"),
    "PP_MIN_IDLE_TIME": CommandSpec(17, 71, 1, "ro", "uint32", "PP min idle"),
    "PP_RESET_MIN_IDLE_TIME": CommandSpec(17, 72, 1, "wo", "uint32", "Reset PP min idle"),
    "PP_AGCONOFF": CommandSpec(17, 10, 1, "rw", "int32", "AGC enable"),
    "PP_AGCMAXGAIN": CommandSpec(17, 11, 1, "rw", "float", "AGC max gain"),
    "PP_AGCDESIREDLEVEL": CommandSpec(17, 12, 1, "rw", "float", "AGC desired level"),
    "PP_AGCGAIN": CommandSpec(17, 13, 1, "rw", "float", "AGC gain"),
    "PP_AGCTIME": CommandSpec(17, 14, 1, "rw", "float", "AGC time"),
    "PP_AGCFASTTIME": CommandSpec(17, 15, 1, "rw", "float", "AGC fast time"),
    "PP_AGCALPHAFASTGAIN": CommandSpec(17, 16, 1, "rw", "float", "AGC alpha fast gain"),
    "PP_AGCALPHASLOW": CommandSpec(17, 17, 1, "rw", "float", "AGC alpha slow"),
    "PP_AGCALPHAFAST": CommandSpec(17, 18, 1, "rw", "float", "AGC alpha fast"),
    "PP_LIMITONOFF": CommandSpec(17, 19, 1, "rw", "int32", "Limiter enable"),
    "PP_LIMITPLIMIT": CommandSpec(17, 20, 1, "rw", "float", "Limiter limit"),
    "PP_MIN_NS": CommandSpec(17, 21, 1, "rw", "float", "Noise suppression min ns"),
    "PP_MIN_NN": CommandSpec(17, 22, 1, "rw", "float", "Noise suppression min nn"),
    "PP_ECHOONOFF": CommandSpec(17, 23, 1, "rw", "int32", "Echo suppression"),
    "PP_GAMMA_E": CommandSpec(17, 24, 1, "rw", "float", "Echo gamma e"),
    "PP_GAMMA_ETAIL": CommandSpec(17, 25, 1, "rw", "float", "Echo gamma etail"),
    "PP_GAMMA_ENL": CommandSpec(17, 26, 1, "rw", "float", "Echo gamma enl"),
    "PP_NLATTENONOFF": CommandSpec(17, 27, 1, "rw", "int32", "Non-linear attenuation"),
    "PP_NLAEC_MODE": CommandSpec(17, 28, 1, "rw", "int32", "NLAEC mode"),
    "PP_MGSCALE": CommandSpec(17, 29, 3, "rw", "float", "Minimum gain scale"),
    "PP_FMIN_SPEINDEX": CommandSpec(17, 30, 1, "rw", "float", "Speech index threshold"),
    "PP_DTSENSITIVE": CommandSpec(17, 31, 1, "rw", "int32", "Double talk sensitivity"),
    "PP_ATTNS_MODE": CommandSpec(17, 32, 1, "rw", "int32", "Attenuation mode"),
    "PP_ATTNS_NOMINAL": CommandSpec(17, 33, 1, "rw", "float", "Attenuation nominal"),
    "PP_ATTNS_SLOPE": CommandSpec(17, 34, 1, "rw", "float", "Attenuation slope"),
}
